# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taskbob Blog
email: blogger@taskbob.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of taskbob.com, the go-to destination for getting reliable home
  services (handymen, appliance repair, deep cleaning, car spa,
  temporary maids) in Mumbai
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taskbob.com" # the base hostname & protocol for your site
twitter_username: taskbob
github_username:  taskbob

# Build settings
markdown: kramdown

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Fun"
              value: "fun"
            - name: "Announcement"
              value: "announcement"
